apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blue-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: nginx
        color: blue
    spec:
      containers:
        - name: nginx
          image: localhost:5000/blue
          ports:
            - name: http
              containerPort: 80
