apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: green-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: nginx
        color: green
    spec:
      containers:
        - name: nginx
          image: localhost:5000/green
          ports:
            - name: http
              containerPort: 80
